# Generated by Django 3.2.12 on 2022-02-04 20:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wagtail_legacy_hallo_editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallopage',
            name='body_hallo',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hallopage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
