# Generated by Django 3.2.12 on 2022-02-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wagtail_legacy_hallo_editor', '0002_auto_20220204_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallopage',
            name='body_hallo',
        ),
    ]
