# Generated by Django 3.2.6 on 2021-09-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadpage',
            name='archived_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
