# Generated by Django 3.2.6 on 2021-08-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadpage',
            name='status',
            field=models.CharField(choices=[('O', 'Offen'), ('T', 'Vergeben'), ('W', 'In Arbeit'), ('C', 'Komplett'), ('A', 'Abgebrochen')], default='O', max_length=1),
        ),
    ]
