# Generated by Django 3.2.6 on 2021-08-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0004_breadpage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadpage',
            name='status',
            field=models.TextField(choices=[('O', 'Offen'), ('T', 'Vergeben'), ('W', 'In Arbeit'), ('C', 'Komplett'), ('A', 'Abgebrochen')], default='O', max_length=1),
        ),
    ]
