# Generated by Django 3.2.6 on 2021-09-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0004_breadpage_archived_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadpage',
            name='archived_on',
        ),
    ]
