# Generated by Django 3.2.6 on 2021-09-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0005_remove_breadpage_archived_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadpage',
            name='archived_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
