# Generated by Django 3.2.6 on 2021-08-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helparticle',
            name='url_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
