# Generated by Django 4.0.7 on 2022-10-18 20:09

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='steps',
            field=wagtail.fields.StreamField([('heading_block', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock()), ('attribute_name', wagtail.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))]))], blank=True, help_text='The steps this process takes towards its end', use_json_field=True, verbose_name='Steps'),
        ),
    ]
