# Generated by Django 4.0.7 on 2022-10-18 20:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_process_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('process', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start', to='process.process')),
            ],
        ),
    ]
