# Generated by Django 4.0.7 on 2022-10-18 20:20

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_alter_process_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='steps',
            field=wagtail.fields.StreamField([('step_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False))])), ('end_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False))]))], blank=True, help_text='The steps this process takes towards its end', use_json_field=True, verbose_name='Steps'),
        ),
    ]
