# Generated by Django 4.0.7 on 2022-10-18 21:20

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_alter_process_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='start',
            field=wagtail.fields.StreamField([('start', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False))]))], blank=True, help_text='The steps this process takes towards its end', use_json_field=True, verbose_name='Steps'),
        ),
        migrations.AlterField(
            model_name='process',
            name='steps',
            field=wagtail.fields.StreamField([('task_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False))])), ('event_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False))])), ('document_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock())])), ('end_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False))])), ('exclusive_gateway_block', wagtail.blocks.StreamBlock([('task_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False))])), ('event_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False))])), ('document_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock())])), ('end_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False))]))]))], blank=True, help_text='The steps this process takes towards its end', use_json_field=True, verbose_name='Steps'),
        ),
        migrations.DeleteModel(
            name='ProcessStart',
        ),
    ]
