# Generated by Django 4.0.7 on 2022-10-18 21:43

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_process_start_alter_process_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='start',
            field=wagtail.fields.StreamField([('start_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False))]))], blank=True, help_text='How does this process start?', use_json_field=True, verbose_name='Start'),
        ),
    ]
