# Generated by Django 4.0.7 on 2022-10-18 22:24

import bakerydemo.process.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_process_latest_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='steps',
            field=wagtail.fields.StreamField([('task_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False))])), ('event_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False))])), ('document_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock())])), ('exclusive_gateway_block', bakerydemo.process.blocks.ExclusiveGatewayListBlock()), ('end_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(blank=True, required=False))]))], blank=True, help_text='The steps this process takes towards its end', use_json_field=True, verbose_name='Steps'),
        ),
    ]
