# Generated by Django 3.2.6 on 2021-08-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
