# Generated by Django 3.0.5 on 2020-05-04 01:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='ingredients',
            field=wagtail.core.fields.StreamField([('ingredients_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('ingredient', wagtail.core.blocks.CharBlock()), ('amount', wagtail.core.blocks.CharBlock(required=False))], form_classname='some-ingredient'), form_classname='ingredients-list'))], default=None),
            preserve_default=False,
        ),
    ]
