# Generated by Django 3.0.5 on 2020-04-29 10:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_test_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='test_a',
            field=wagtail.core.fields.StreamField([('privacy', wagtail.core.blocks.StructBlock([('visible_groups', wagtail.core.blocks.ListBlock(wagtail.core.blocks.ChooserBlock(blank=True, label='Limit view to groups', required=False, target_model='django.contrib.auth.groups')))], blank=True))]),
        ),
    ]
