# Generated by Django 3.0.5 on 2020-05-04 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200504_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='ingredients',
        ),
    ]
