# Generated by Django 3.0.5 on 2020-05-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200429_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='test_a',
        ),
    ]
