# Generated by Django 3.0.5 on 2020-04-17 03:19

import bakerydemo.locations.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_locationpage_test_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpage',
            name='test_a',
            field=wagtail.core.fields.StreamField([('Map', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title', required=True)), ('content', wagtail.core.blocks.RichTextBlock(label='Content', required=False)), ('ip_address', bakerydemo.locations.models.IPAddressBlock(label='IP Address', required=False))]))]),
        ),
    ]
