# Generated by Django 3.0.5 on 2020-04-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20200417_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationpage',
            name='test_a',
        ),
    ]
