# Generated by Django 3.0.5 on 2020-04-17 03:29

import bakerydemo.locations.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_remove_locationpage_test_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='test_b',
            field=wagtail.core.fields.StreamField([('Map', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title', required=False)), ('content', wagtail.core.blocks.RichTextBlock(label='Content', required=False)), ('tags', bakerydemo.locations.models.TagsBlock(label='Tags', required=False))], required=False))], blank=True),
        ),
    ]
