# Generated by Django 3.0.5 on 2020-04-17 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_locationpage_test_b'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationpage',
            old_name='test_b',
            new_name='map_info',
        ),
    ]
