# Generated by Django 3.0.5 on 2020-04-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20200417_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationpage',
            name='map_info',
        ),
    ]
