# Generated by Django 3.0.5 on 2020-05-06 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('base', '0004_auto_20180522_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='modal_form_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Modal Form'),
        ),
    ]
