# Generated by Django 2.2.4 on 2020-01-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180522_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='no_index',
            field=models.BooleanField(default=False),
        ),
    ]
