# Generated by Django 2.2.4 on 2020-01-12 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('base', '0005_animalpage_animalspage_articlepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='animals',
        ),
        migrations.AddField(
            model_name='animalpage',
            name='article_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
