# Generated by Django 3.2.6 on 2021-08-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_formfield_clean_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='field_classname',
            field=models.CharField(blank=True, max_length=254, verbose_name='Field classes'),
        ),
    ]
