# Generated by Django 3.2.6 on 2021-09-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('base', '0005_formfield_clean_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistApprovalTask',
            fields=[
                ('groupapprovaltask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.groupapprovaltask')),
                ('checklist', models.TextField(help_text='Each line will become a checklist item shown on the Approve step.', verbose_name='Checklist')),
                ('is_checklist_required', models.BooleanField(blank=True, help_text='If required, all items in the checklist must be ticked to approve.', verbose_name='Required')),
            ],
            options={
                'verbose_name': 'Checklist approval task',
                'verbose_name_plural': 'Checklist approval tasks',
            },
            bases=('wagtailcore.groupapprovaltask',),
        ),
    ]
