# Generated by Django 3.2.6 on 2021-08-26 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('base', '0005_formfield_clean_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrosscheckApprovalTask',
            fields=[
                ('groupapprovaltask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.groupapprovaltask')),
                ('checklist', models.TextField(help_text='Each line will become a checklist item.', verbose_name='Checklist')),
            ],
            bases=('wagtailcore.groupapprovaltask',),
        ),
    ]
