# Generated by Django 2.2.4 on 2020-01-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_standardpage_no_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='no_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepage',
            name='no_index',
            field=models.BooleanField(default=False),
        ),
    ]
