# Generated by Django 3.0.5 on 2020-05-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200506_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAppSettings',
        ),
    ]
