# Generated by Django 3.2.6 on 2021-09-05 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('base', '0006_splitgroupapprovaltask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SplitGroupApprovalTask',
        ),
    ]
