# Generated by Django 3.2.12 on 2022-02-05 04:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_hallotestpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallotestpage',
            name='body_stream',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(editor='legacy'))], blank=True),
        ),
    ]
