# Generated by Django 3.0.5 on 2020-05-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_importantpages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='ImportantPages',
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
