# Generated by Django 3.0.5 on 2020-04-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_customabstractformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customabstractformsubmission',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
