# Generated by Django 3.2.6 on 2021-08-11 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('base', '0006_publishsitetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishsitetask',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site'),
        ),
    ]
