# Generated by Django 2.2.4 on 2020-01-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200118_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='no_index',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='no_index',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='no_index',
        ),
    ]
