# Generated by Django 3.0.5 on 2020-09-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0057_page_locale_fields_notnull'),
        ('base', '0006_auto_20200922_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='uploaded_image_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Collection'),
        ),
    ]
