# Generated by Django 3.2.12 on 2022-02-07 22:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_hallotestpage_body_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallotestpage',
            name='body_stream',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(editor='hallo'))], blank=True),
        ),
    ]
