# Generated by Django 3.2.6 on 2021-09-05 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0007_delete_splitgroupapprovaltask'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitGroupApprovalTask',
            fields=[
                ('groupapprovaltask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.groupapprovaltask')),
                ('groups_a', models.ManyToManyField(help_text='Pages at this step in a workflow will be moderated or approved by these groups of users', related_name='split_task_group_a', to='auth.Group')),
                ('groups_b', models.ManyToManyField(help_text='Pages at this step in a workflow will be moderated or approved by these groups of users', related_name='split_task_group_b', to='auth.Group')),
            ],
            bases=('wagtailcore.groupapprovaltask',),
        ),
    ]
