# Generated by Django 3.0.5 on 2020-04-21 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('base', '0007_customabstractformsubmission_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormUploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='wagtailforms.FormSubmission')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomAbstractFormSubmission',
        ),
    ]
