# Generated by Django 3.2.6 on 2021-09-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='field_classname',
            field=models.CharField(blank=True, max_length=255, verbose_name='temp'),
        ),
    ]
