# Generated by Django 3.0.5 on 2020-04-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200421_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formuploadedfile',
            name='form_submission',
        ),
    ]
