# Generated by Django 3.0.5 on 2020-05-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_myappsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAppSettings',
        ),
    ]
