# Generated by Django 3.0.5 on 2020-04-21 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('base', '0009_remove_formuploadedfile_form_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='formuploadedfile',
            name='field_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='formuploadedfile',
            name='form_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='wagtailforms.FormSubmission'),
        ),
    ]
