# Generated by Django 3.2.6 on 2021-09-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_formfield_field_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='field_classname',
        ),
    ]
