# Generated by Django 3.2.12 on 2022-02-08 10:42

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_pagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='bio',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
