# Generated by Django 4.0.10 on 2023-04-23 07:43

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_person_expire_at_person_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='testing_content',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
