# Generated by Django 4.0.10 on 2023-04-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_standardpage_draftail_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='draftail_content',
        ),
    ]
