# Generated by Django 3.0.5 on 2020-05-17 02:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rocket_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_url', models.URLField(blank=True, null=True)),
                ('submitted_by', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('PROPOSED', 'Proposed'), ('HOLD', 'Hold'), ('CURRENT', 'Current')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', wagtail.core.fields.RichTextField(blank=True)),
                ('category', models.CharField(choices=[('BLANK', 'Uncategorised'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='BLANK', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RocketReportPageReportPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='rocket_reports', to='rocket_report.RocketReportPage')),
                ('rocket_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rocket_report.RocketReport')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
