# Generated by Django 4.0.2 on 2022-02-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schematics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schematicpoint",
            options={"verbose_name": "Point", "verbose_name_plural": "Points"},
        ),
        migrations.AddField(
            model_name="schematicpoint",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="schematicpoint",
            name="label",
            field=models.CharField(default="", max_length=254, verbose_name="Label"),
            preserve_default=False,
        ),
    ]
