# Generated by Django 4.0.2 on 2022-02-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schematics", "0002_alter_schematicpoint_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schematicpoint",
            name="description",
        ),
    ]
