# Generated by Django 4.0.2 on 2022-02-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schematics", "0004_alter_schematic_options_productpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpage",
            name="schematic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_page_schematic",
                to="schematics.schematic",
            ),
        ),
    ]
